GET https://dog.ceo/api/breeds/image/random

###

GET https://dog.ceo/api/breeds/list/all

###

POST https://dog.ceo/api/breeds/list/all
Content-Type: application/json

{
    "name" :"";
    "age" :"";
}